sudo: required
services:
  - docker

before_install:
  - docker build -t nastaran74/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nastaran74/react-test npm test -- --coverage

after_success:
  - docker build -t nastaran74/multi-client ./client
  - docker build -t nastaran74/multi-nginx ./nginx
  - docker build -t nastaran74/multi-server ./server
  - docker build -t nastaran74/multi-worker ./worker